name: alpha

on:
  workflow_dispatch:
  push:
    branches: [ "cloudflare" ]
  pull_request:
    branches: [ "cloudflare" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Install linters and formatters
      run: |
        npm install eslint   --save-dev
        npm install prettier --save-dev

    - name: Install sass
      run: npm install sass --save-dev

    - name: Release
      run: make release

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/html
        name: yam-alpha

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/linux/yam
        name: yam_linux-alpha

    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/darwin-x64/yam
        name: yam_darwin-x64-alpha

    - name: Upload MacOS Apple silicon artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/darwin-arm64/yam
        name: yam_darwin-arm64-alpha

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/windows/yam.exe
        name: yam_windows-alpha.exe

    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/arm/yam
        name: yam_arm-alpha

    - name: Upload ARMv7 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/arm7/yam
        name: yam_arm7-alpha

    - name: Upload ARMv6 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam/arm6/yam
        name: yam_arm6-alpha
