name: nightly

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install linters and formatters
      run: |
        npm install eslint   --save-dev
        npm install prettier --save-dev

    - name: Install sass
      run: npm install sass --save-dev

    - name: Build release
      run: make release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/yam
        name: yam-nightly
